export const banderas = {
  "México": "https://flagcdn.com/w40/mx.png",
  "Sudáfrica": "https://flagcdn.com/w40/za.png",
  "Corea del Sur": "https://flagcdn.com/w40/kr.png",
  "República Checa": "https://flagcdn.com/w40/cz.png",
  "Canadá": "https://flagcdn.com/w40/ca.png",
  "Bosnia": "https://flagcdn.com/w40/ba.png",
  "Qatar": "https://flagcdn.com/w40/qa.png",
  "Suiza": "https://flagcdn.com/w40/ch.png",
  "Brasil": "https://flagcdn.com/w40/br.png",
  "Marruecos": "https://flagcdn.com/w40/ma.png",
  "Haití": "https://flagcdn.com/w40/ht.png",
  "Escocia": "https://flagcdn.com/w40/gb-sct.png",
  "Estados Unidos": "https://flagcdn.com/w40/us.png",
  "Paraguay": "https://flagcdn.com/w40/py.png",
  "Australia": "https://flagcdn.com/w40/au.png",
  "Turquía": "https://flagcdn.com/w40/tr.png",
  "Alemania": "https://flagcdn.com/w40/de.png",
  "Curazao": "https://flagcdn.com/w40/cw.png",
  "Costa de Marfil": "https://flagcdn.com/w40/ci.png",
  "Ecuador": "https://flagcdn.com/w40/ec.png",
  "Países Bajos": "https://flagcdn.com/w40/nl.png",
  "Japón": "https://flagcdn.com/w40/jp.png",
  "Suecia": "https://flagcdn.com/w40/se.png",
  "Túnez": "https://flagcdn.com/w40/tn.png",
  "Bélgica": "https://flagcdn.com/w40/be.png",
  "Egipto": "https://flagcdn.com/w40/eg.png",
  "Irán": "https://flagcdn.com/w40/ir.png",
  "Nueva Zelanda": "https://flagcdn.com/w40/nz.png",
  "España": "https://flagcdn.com/w40/es.png",
  "Cabo Verde": "https://flagcdn.com/w40/cv.png",
  "Arabia Saudita": "https://flagcdn.com/w40/sa.png",
  "Uruguay": "https://flagcdn.com/w40/uy.png",
  "Francia": "https://flagcdn.com/w40/fr.png",
  "Senegal": "https://flagcdn.com/w40/sn.png",
  "Irak": "https://flagcdn.com/w40/iq.png",
  "Noruega": "https://flagcdn.com/w40/no.png",
  "Argentina": "https://flagcdn.com/w40/ar.png",
  "Argelia": "https://flagcdn.com/w40/dz.png",
  "Austria": "https://flagcdn.com/w40/at.png",
  "Jordania": "https://flagcdn.com/w40/jo.png",
  "Portugal": "https://flagcdn.com/w40/pt.png",
  "Congo DR": "https://flagcdn.com/w40/cd.png",
  "Uzbekistán": "https://flagcdn.com/w40/uz.png",
  "Colombia": "https://flagcdn.com/w40/co.png",
  "Inglaterra": "https://flagcdn.com/w40/gb-eng.png",
  "Croacia": "https://flagcdn.com/w40/hr.png",
  "Panamá": "https://flagcdn.com/w40/pa.png",
  "Ghana": "https://flagcdn.com/w40/gh.png",
};