export const fixtureData = [
  // =========================
  // GRUPO A
  // =========================
  {
    id: 1,
    grupo: "A",
    fecha: "2026-06-11",
    estadio: "Estadio Azteca",
    local: "México",
    visitante: "Sudáfrica",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 2,
    grupo: "A",
    fecha: "2026-06-12",
    estadio: "Toronto Stadium",
    local: "Corea del Sur",
    visitante: "República Checa",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 3,
    grupo: "A",
    fecha: "2026-06-16",
    estadio: "Estadio Azteca",
    local: "México",
    visitante: "Corea del Sur",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 4,
    grupo: "A",
    fecha: "2026-06-17",
    estadio: "Toronto Stadium",
    local: "Sudáfrica",
    visitante: "República Checa",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 5,
    grupo: "A",
    fecha: "2026-06-21",
    estadio: "Estadio Azteca",
    local: "México",
    visitante: "República Checa",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 6,
    grupo: "A",
    fecha: "2026-06-21",
    estadio: "Toronto Stadium",
    local: "Sudáfrica",
    visitante: "Corea del Sur",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO B
  // =========================
  {
    id: 7,
    grupo: "B",
    fecha: "2026-06-12",
    estadio: "Vancouver Stadium",
    local: "Canadá",
    visitante: "Bosnia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 8,
    grupo: "B",
    fecha: "2026-06-12",
    estadio: "MetLife Stadium",
    local: "Qatar",
    visitante: "Suiza",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 9,
    grupo: "B",
    fecha: "2026-06-16",
    estadio: "Vancouver Stadium",
    local: "Canadá",
    visitante: "Qatar",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 10,
    grupo: "B",
    fecha: "2026-06-17",
    estadio: "MetLife Stadium",
    local: "Bosnia",
    visitante: "Suiza",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 11,
    grupo: "B",
    fecha: "2026-06-22",
    estadio: "Vancouver Stadium",
    local: "Canadá",
    visitante: "Suiza",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 12,
    grupo: "B",
    fecha: "2026-06-22",
    estadio: "MetLife Stadium",
    local: "Bosnia",
    visitante: "Qatar",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO C
  // =========================
  {
    id: 13,
    grupo: "C",
    fecha: "2026-06-13",
    estadio: "SoFi Stadium",
    local: "Brasil",
    visitante: "Marruecos",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 14,
    grupo: "C",
    fecha: "2026-06-13",
    estadio: "Hard Rock Stadium",
    local: "Haití",
    visitante: "Escocia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 15,
    grupo: "C",
    fecha: "2026-06-17",
    estadio: "SoFi Stadium",
    local: "Brasil",
    visitante: "Haití",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 16,
    grupo: "C",
    fecha: "2026-06-17",
    estadio: "Hard Rock Stadium",
    local: "Marruecos",
    visitante: "Escocia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 17,
    grupo: "C",
    fecha: "2026-06-22",
    estadio: "SoFi Stadium",
    local: "Brasil",
    visitante: "Escocia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 18,
    grupo: "C",
    fecha: "2026-06-22",
    estadio: "Hard Rock Stadium",
    local: "Marruecos",
    visitante: "Haití",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO D
  // =========================
  {
    id: 19,
    grupo: "D",
    fecha: "2026-06-13",
    estadio: "AT&T Stadium",
    local: "Estados Unidos",
    visitante: "Paraguay",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 20,
    grupo: "D",
    fecha: "2026-06-14",
    estadio: "Lumen Field",
    local: "Australia",
    visitante: "Turquía",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 21,
    grupo: "D",
    fecha: "2026-06-18",
    estadio: "AT&T Stadium",
    local: "Estados Unidos",
    visitante: "Australia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 22,
    grupo: "D",
    fecha: "2026-06-18",
    estadio: "Lumen Field",
    local: "Paraguay",
    visitante: "Turquía",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 23,
    grupo: "D",
    fecha: "2026-06-23",
    estadio: "AT&T Stadium",
    local: "Estados Unidos",
    visitante: "Turquía",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 24,
    grupo: "D",
    fecha: "2026-06-23",
    estadio: "Lumen Field",
    local: "Paraguay",
    visitante: "Australia",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO E
  // =========================
  {
    id: 25,
    grupo: "E",
    fecha: "2026-06-14",
    estadio: "Mercedes-Benz Stadium",
    local: "Alemania",
    visitante: "Curazao",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 26,
    grupo: "E",
    fecha: "2026-06-14",
    estadio: "NRG Stadium",
    local: "Costa de Marfil",
    visitante: "Ecuador",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 27,
    grupo: "E",
    fecha: "2026-06-18",
    estadio: "Mercedes-Benz Stadium",
    local: "Alemania",
    visitante: "Costa de Marfil",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 28,
    grupo: "E",
    fecha: "2026-06-19",
    estadio: "NRG Stadium",
    local: "Curazao",
    visitante: "Ecuador",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 29,
    grupo: "E",
    fecha: "2026-06-23",
    estadio: "Mercedes-Benz Stadium",
    local: "Alemania",
    visitante: "Ecuador",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 30,
    grupo: "E",
    fecha: "2026-06-23",
    estadio: "NRG Stadium",
    local: "Curazao",
    visitante: "Costa de Marfil",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO F
  // =========================
  {
    id: 31,
    grupo: "F",
    fecha: "2026-06-15",
    estadio: "Levi's Stadium",
    local: "Países Bajos",
    visitante: "Japón",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 32,
    grupo: "F",
    fecha: "2026-06-15",
    estadio: "Arrowhead Stadium",
    local: "Suecia",
    visitante: "Túnez",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 33,
    grupo: "F",
    fecha: "2026-06-19",
    estadio: "Levi's Stadium",
    local: "Países Bajos",
    visitante: "Suecia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 34,
    grupo: "F",
    fecha: "2026-06-19",
    estadio: "Arrowhead Stadium",
    local: "Japón",
    visitante: "Túnez",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 35,
    grupo: "F",
    fecha: "2026-06-24",
    estadio: "Levi's Stadium",
    local: "Países Bajos",
    visitante: "Túnez",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 36,
    grupo: "F",
    fecha: "2026-06-24",
    estadio: "Arrowhead Stadium",
    local: "Japón",
    visitante: "Suecia",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO G
  // =========================
  {
    id: 37,
    grupo: "G",
    fecha: "2026-06-15",
    estadio: "Lincoln Financial Field",
    local: "Bélgica",
    visitante: "Egipto",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 38,
    grupo: "G",
    fecha: "2026-06-15",
    estadio: "BC Place",
    local: "Irán",
    visitante: "Nueva Zelanda",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 39,
    grupo: "G",
    fecha: "2026-06-19",
    estadio: "Lincoln Financial Field",
    local: "Bélgica",
    visitante: "Irán",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 40,
    grupo: "G",
    fecha: "2026-06-20",
    estadio: "BC Place",
    local: "Egipto",
    visitante: "Nueva Zelanda",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 41,
    grupo: "G",
    fecha: "2026-06-24",
    estadio: "Lincoln Financial Field",
    local: "Bélgica",
    visitante: "Nueva Zelanda",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 42,
    grupo: "G",
    fecha: "2026-06-24",
    estadio: "BC Place",
    local: "Egipto",
    visitante: "Irán",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO H
  // =========================
  {
    id: 43,
    grupo: "H",
    fecha: "2026-06-16",
    estadio: "MetLife Stadium",
    local: "España",
    visitante: "Cabo Verde",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 44,
    grupo: "H",
    fecha: "2026-06-16",
    estadio: "SoFi Stadium",
    local: "Arabia Saudita",
    visitante: "Uruguay",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 45,
    grupo: "H",
    fecha: "2026-06-20",
    estadio: "MetLife Stadium",
    local: "España",
    visitante: "Arabia Saudita",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 46,
    grupo: "H",
    fecha: "2026-06-20",
    estadio: "SoFi Stadium",
    local: "Cabo Verde",
    visitante: "Uruguay",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 47,
    grupo: "H",
    fecha: "2026-06-25",
    estadio: "MetLife Stadium",
    local: "España",
    visitante: "Uruguay",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 48,
    grupo: "H",
    fecha: "2026-06-25",
    estadio: "SoFi Stadium",
    local: "Cabo Verde",
    visitante: "Arabia Saudita",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO I
  // =========================
  {
    id: 49,
    grupo: "I",
    fecha: "2026-06-16",
    estadio: "Gillette Stadium",
    local: "Francia",
    visitante: "Senegal",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 50,
    grupo: "I",
    fecha: "2026-06-17",
    estadio: "NRG Stadium",
    local: "Irak",
    visitante: "Noruega",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 51,
    grupo: "I",
    fecha: "2026-06-21",
    estadio: "Gillette Stadium",
    local: "Francia",
    visitante: "Irak",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 52,
    grupo: "I",
    fecha: "2026-06-21",
    estadio: "NRG Stadium",
    local: "Senegal",
    visitante: "Noruega",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 53,
    grupo: "I",
    fecha: "2026-06-25",
    estadio: "Gillette Stadium",
    local: "Francia",
    visitante: "Noruega",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 54,
    grupo: "I",
    fecha: "2026-06-25",
    estadio: "NRG Stadium",
    local: "Senegal",
    visitante: "Irak",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO J
  // =========================
  {
    id: 55,
    grupo: "J",
    fecha: "2026-06-17",
    estadio: "Hard Rock Stadium",
    local: "Argentina",
    visitante: "Argelia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 56,
    grupo: "J",
    fecha: "2026-06-17",
    estadio: "Arrowhead Stadium",
    local: "Austria",
    visitante: "Jordania",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 57,
    grupo: "J",
    fecha: "2026-06-21",
    estadio: "Hard Rock Stadium",
    local: "Argentina",
    visitante: "Austria",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 58,
    grupo: "J",
    fecha: "2026-06-22",
    estadio: "Arrowhead Stadium",
    local: "Argelia",
    visitante: "Jordania",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 59,
    grupo: "J",
    fecha: "2026-06-26",
    estadio: "Hard Rock Stadium",
    local: "Argentina",
    visitante: "Jordania",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 60,
    grupo: "J",
    fecha: "2026-06-26",
    estadio: "Arrowhead Stadium",
    local: "Argelia",
    visitante: "Austria",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO K
  // =========================
  {
    id: 61,
    grupo: "K",
    fecha: "2026-06-18",
    estadio: "Levi's Stadium",
    local: "Portugal",
    visitante: "Congo DR",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 62,
    grupo: "K",
    fecha: "2026-06-18",
    estadio: "Lumen Field",
    local: "Uzbekistán",
    visitante: "Colombia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 63,
    grupo: "K",
    fecha: "2026-06-22",
    estadio: "Levi's Stadium",
    local: "Portugal",
    visitante: "Uzbekistán",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 64,
    grupo: "K",
    fecha: "2026-06-22",
    estadio: "Lumen Field",
    local: "Congo DR",
    visitante: "Colombia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 65,
    grupo: "K",
    fecha: "2026-06-26",
    estadio: "Levi's Stadium",
    local: "Portugal",
    visitante: "Colombia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 66,
    grupo: "K",
    fecha: "2026-06-26",
    estadio: "Lumen Field",
    local: "Congo DR",
    visitante: "Uzbekistán",
    golesLocal: null,
    golesVisitante: null,
  },

  // =========================
  // GRUPO L
  // =========================
  {
    id: 67,
    grupo: "L",
    fecha: "2026-06-18",
    estadio: "AT&T Stadium",
    local: "Inglaterra",
    visitante: "Croacia",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 68,
    grupo: "L",
    fecha: "2026-06-18",
    estadio: "Mercedes-Benz Stadium",
    local: "Panamá",
    visitante: "Ghana",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 69,
    grupo: "L",
    fecha: "2026-06-22",
    estadio: "AT&T Stadium",
    local: "Inglaterra",
    visitante: "Panamá",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 70,
    grupo: "L",
    fecha: "2026-06-23",
    estadio: "Mercedes-Benz Stadium",
    local: "Croacia",
    visitante: "Ghana",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 71,
    grupo: "L",
    fecha: "2026-06-26",
    estadio: "AT&T Stadium",
    local: "Inglaterra",
    visitante: "Ghana",
    golesLocal: null,
    golesVisitante: null,
  },
  {
    id: 72,
    grupo: "L",
    fecha: "2026-06-26",
    estadio: "Mercedes-Benz Stadium",
    local: "Croacia",
    visitante: "Panamá",
    golesLocal: null,
    golesVisitante: null,
  }
];

// Generamos automáticamente el fixture con la fecha límite ya calculada (1 día antes)
export const fixtureConLimite = fixtureData.map(partido => {
  const fechaPartido = new Date(`${partido.fecha}T00:00:00`);
  fechaPartido.setDate(fechaPartido.getDate() - 1); // Restamos 1 día
  
  // Formateamos la fecha límite a YYYY-MM-DD
  const year = fechaPartido.getFullYear();
  const month = String(fechaPartido.getMonth() + 1).padStart(2, '0');
  const day = String(fechaPartido.getDate()).padStart(2, '0');
  
  return {
    ...partido,
    fechaLimite: `${year}-${month}-${day}` // Ejemplo: "2026-06-10"
  };
});